// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8PX0L1tXvbK170kR73T-sJbgl7Jxj6L0',
    appId: '1:28223984247:web:c042adf6904e5dff462c72',
    messagingSenderId: '28223984247',
    projectId: 'stock-app-cab2a',
    authDomain: 'stock-app-cab2a.firebaseapp.com',
    storageBucket: 'stock-app-cab2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7l2p2X4XfOWYD1LBy5JQLXDdduMtcdWk',
    appId: '1:28223984247:android:03fadb2c54048910462c72',
    messagingSenderId: '28223984247',
    projectId: 'stock-app-cab2a',
    storageBucket: 'stock-app-cab2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9PlAicWo3Ehl8S0uZeiewtERCKFKm1o',
    appId: '1:28223984247:ios:8400a4c732171cdc462c72',
    messagingSenderId: '28223984247',
    projectId: 'stock-app-cab2a',
    storageBucket: 'stock-app-cab2a.firebasestorage.app',
    androidClientId: '28223984247-afnjovofmqco1v1r8oo0tf0idjrdlo3v.apps.googleusercontent.com',
    iosClientId: '28223984247-7hgb9td1eff35mc8bhoov4trg0ma2e8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9PlAicWo3Ehl8S0uZeiewtERCKFKm1o',
    appId: '1:28223984247:ios:8400a4c732171cdc462c72',
    messagingSenderId: '28223984247',
    projectId: 'stock-app-cab2a',
    storageBucket: 'stock-app-cab2a.firebasestorage.app',
    androidClientId: '28223984247-afnjovofmqco1v1r8oo0tf0idjrdlo3v.apps.googleusercontent.com',
    iosClientId: '28223984247-7hgb9td1eff35mc8bhoov4trg0ma2e8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8PX0L1tXvbK170kR73T-sJbgl7Jxj6L0',
    appId: '1:28223984247:web:a8b2374040ecfe36462c72',
    messagingSenderId: '28223984247',
    projectId: 'stock-app-cab2a',
    authDomain: 'stock-app-cab2a.firebaseapp.com',
    storageBucket: 'stock-app-cab2a.firebasestorage.app',
  );
}
